### ISSUE TITLE
Feature request for Spectrum Next users to allow to connect through ESP8266 wifi

### ISSUE THREAD

**Issue by simulant-systems** [thweasel/snapCterm#7]
Hi I just wondered if you may be able to add the option in SnapCTerm so that Spectrum Next users can use their built in Wifi to connect to a BBS?

I run a humble Amstrad BBS: [https://amstrad.simulant.uk](url)

and a user there who knows you posted about SnapCTerm which is how I came across your project! Thanks for such a great Terminal program.

I recently got my Spectrum Next, however currently it is lacking a good terminal emulator. As the Next is 100% compatible with actual ZX Spectrum peripherals and interfaces it can already use SnapCTerm if an interface can be added that has an rs232 serial port. However the Next also can house built in Wifi with its own ESP8266 fitted. When I ordered my Next I got the wifi variant and it would be great to just connect over wifi with SnapCTerm.

I hope this is please possible and I am more than happy to help if I can in terms of testing if you need any information etc to add the feature.

Thanks again and hope you will consider it  :)

**Comment by thweasel** [comment]
Hi Simulant-systems, 

I know your BBS well I used it to test SnapCTerm as I built it!  I don't have a NEXT (yet), and they haven't yet got a working library similar to the serial ports or Spectranet adapter yet (or at least the last time I looked).  At some point, I will either learn assembler and contribute one to z88dk or someone else will that I can use.  To port snapCterm as is using traditional spectrum graphic mode would be as easy as writing a few network routines and extending the make script.

Sorry for the late reply!
