### ISSUE TITLE
.tap file just restarts machine

### ISSUE THREAD

**Issue by zoggins** [thweasel/snapCterm#8]
I built the code and on both my 128k and +2A the program loads and just restarts the machine.  It does with a DivMMC, MB03+ and a tape emulator.   Not sure what I am doing wrong.  Thanks.

**Comment by thweasel** [comment]
Hi, sorry for the late reply I have been far off down another rabbit hole.  OK, I would ask if you could load the software on the stock machines i.e. remove the addons and see if it fails the same.  It has been tested with a DivMMC and we did find issues with loading the software from the NMI system that pushes TAP files to RAM.  However, the issue spotted was that the keyboard mode registers we left in an unexpected state after the NMI loader finished.

There are some compiled versions on TAP available at 8bitecho.weebly.com/files; might be worth trying one from there.

**Comment by thweasel** [comment]
Having updated to Z88DK 2.1 (release version), there seems to be a problem with zx_pxy2saddr(). The method no longer accepts the mask as a value 255; passing a pointer doesn't seem to help either. So I have replaced the cursor address decoding in void DrawCursor(void), which now compiles and runs.
