### ISSUE TITLE
Next support

### ISSUE THREAD

**Issue by danboid** [thweasel/snapCterm#9]
I'm wanting to use telnet on my xberry pi. This sounded like the app I needed but when I built it I ddn't get a .nex file as I hoped.

**Comment by thweasel** [comment]
I'm sorry, but this is for the original systems. If you had the Next act as the original hardware, you could run it on a Next and then use Spectranet.

I have no plans to port this to the next at this time. It requires too much effort (on my part), and there isn't enough interest.
